name: Add new language
on:
  issues:
    types: [ labeled ]
jobs:
  add_new_language:
    permissions:
      contents: write
      issues: write
    runs-on: ubuntu-latest
    if: github.event.label.name == 'new language'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: next-release

# Retrieve po4a installation cache or create it if not found:
      - name: Cache po4a dependencies
        uses: actions/cache@v1.0.3
        id: cache-po4a
        with:
          path: "~/po4a"
          key: ${{ runner.os }}-po4a
      - name: Install or retrieve po4a from cache
        env:
          CACHE_HIT: ${{ steps.cache-po4a.outputs.cache-hit }}

# If CACHE_HIT: true, retrieve the cache. If not, install po4a and its dependencies and copy them all to a folder (~/po4a/) to be cached:
        run: ./_po4a-tools/po4a-cache.sh

# Get language from issue title and create files for it:
      - name: Make new lang directory and create .po files
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_NUM: ${{ github.event.issue.number }}
        run: |
          NEW_LANG=$(sed 's/.*\[\([^]]*\)].*/\1/' <<< "$ISSUE_TITLE")
          if [[ $NEW_LANG =~ ^[a-z]{2}(_[A-Z]{2})?$ ]]; then
            mkdir _translator-files/po/$NEW_LANG
            ./_po4a-tools/po4a-update-templates.sh
            echo "new_lang=$NEW_LANG" >> $GITHUB_ENV
            echo "issue_num=$ISSUE_NUM" >> $GITHUB_ENV
          else
            echo Language code in wrong format
            exit 1
          fi

# Push changes to 'next-release':
      - name: Push changes to repo
        uses: EndBug/add-and-commit@v7
        with:
          branch: next-release
          default_author: github_actions
          message: 'AUTO: Add new language: (${{ env.new_lang }}) #${{ env.issue_num }}'

# Add comment to issue informing of the creation of the language files:
      - name: Add comment to issue
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ env.issue_num }}
          body: |
            - The .po files have been created for **${{ env.new_lang }}** on the `next-release` branch.
            - They can be found in `_translator-files/po/${{ env.new_lang }}/`.
            - Please consult the README file in `_translator-files/` for information on the translation process.

# Create translated .md files. Never pushed to the repo.
      - name: Create translated .md docs and stats
        run: ./_po4a-tools/po4a-create-all-targets.sh

# Build site
      - name: Build the site in the jekyll/builder container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod a+w /srv/jekyll/Gemfile.lock && chmod 777 /srv/jekyll && jekyll build --future"

